#!/usr/bin/env bash
# Embed the hook and status line scripts into the engine as Swift strings.
#
#   Packages/ClaudeControl/Scripts/embed-scripts.sh           # regenerate
#   Packages/ClaudeControl/Scripts/embed-scripts.sh --check   # exit 1 if stale
#
# Writes Sources/ClaudeControl/Engine/Scripts/EmbeddedScripts.swift from
#   Scripts/superpowered-codenotch-hook.py
#   Scripts/superpowered-codenotch-statusline.py
# byte for byte, as raw string literals. Run it after editing either script;
# the EmbeddedScripts test fails while the two are out of step.
#
# Why not SwiftPM resources: the generated Bundle.module accessor needs a copy
# step in both the Xcode and the Command Line Tools build, and a missing bundle
# is a crash at install time. A string constant is always there.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG="$(dirname "$HERE")"
OUT="$PKG/Sources/ClaudeControl/Engine/Scripts/EmbeddedScripts.swift"
MODE="${1:-write}"

python3 - "$HERE/superpowered-codenotch-hook.py" "$HERE/superpowered-codenotch-statusline.py" "$OUT" "$MODE" <<'PY'
import os, sys

hook, status, out, mode = sys.argv[1:5]

def literal(path):
    text = open(path, "rb").read().decode("utf-8")
    if "\r" in text:
        sys.exit(f"{path}: carriage returns are not supported")
    # Enough #s that neither the closing delimiter nor an escape can occur.
    hashes = "#"
    while ('"' + hashes) in text or ('\\' + hashes) in text:
        hashes += "#"
    # A multi-line literal drops the newline before its closing delimiter, so
    # one extra newline keeps the file's own final newline (if it has one).
    return f'{hashes}"""\n{text}\n"""{hashes}'

swift = f"""// Generated by Packages/ClaudeControl/Scripts/embed-scripts.sh. Do not edit.
//
// Byte-for-byte copies of Packages/ClaudeControl/Scripts/*.py. The socket
// placeholder is filled in at install time (see EmbeddedScripts+Install.swift).

nonisolated enum EmbeddedScriptSources {{
    /// {os.path.basename(hook)}
    static let hook = {literal(hook)}

    /// {os.path.basename(status)}
    static let statusLine = {literal(status)}
}}
"""

if mode == "--check":
    current = open(out, encoding="utf-8").read() if os.path.exists(out) else ""
    if current != swift:
        sys.exit(f"{out} is stale: run Packages/ClaudeControl/Scripts/embed-scripts.sh")
    print("embedded scripts are current")
else:
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(swift)
    print(f"wrote {out}")
PY
